# Generated by Django 6.0.7 on 2026-07-31 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0002_alter_eventuser_date_joined'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventuser',
            options={'permissions': [('can_set_user_permissions', 'User can add permissions'), ('can_see_user_permissions', 'User can see permissions list')], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
