# Generated by Django 6.0.7 on 2026-08-04 16:26

from django.db import migrations
from django.contrib.auth.models import Permission
# from django.contrib.contenttypes.models import ContentType

# content_type_global, _ = ContentType.objects.get_or_create(app_label='user_account', model='global')

# def create_custom_permissions(apps, schema_editor):
#     Permission.objects.create(
#         codename='can_manage_users',
#         name='Can manage user settings',
#         content_type=content_type_global
#     )
#     Permission.objects.create(
#         codename='can_update_permissions',
#         name='Can configure users permissions',
#         content_type=content_type_global
#     )

# def rollback_permissions(apps, schema_editor):
#     Permission.objects.filter(
#         content_type=content_type_global,
#         codename__in=['can_manage_users', 'can_update_permissions']
#     ).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0003_alter_eventuser_options'),
    ]

    operations = [
        # migrations.RunPython(
        #     code=create_custom_permissions,
        #     reverse_code=rollback_permissions
        # )
    ]
