# Generated by Django 6.0.7 on 2026-08-04 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_deleted_at_event_deleted_by_event_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(default='created', max_length=50, verbose_name='Action')),
                ('model', models.CharField(max_length=100, verbose_name='Django model')),
                ('object_id', models.IntegerField(verbose_name='Object ID')),
                ('log_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
