events {
}

http {
    server_tokens off;

    upstream app {
        server app:8000;
        # server app2:8001 weight=7 max_fails=3 fail_timeout=30s;
        # server app2:8001 backup;
        
    }

    server {
        listen 80;
        server_name localhost;
        return 301 https://$host$request_uri;
    }

    server {
        listen 443 ssl;
        server_name localhost;

        ssl_certificate /etc/nginx/certs/cert.crt;
        ssl_certificate_key /etc/nginx/certs/cert.key;

        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_prefer_server_ciphers on;
        ssl_ciphers "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384";
        ssl_session_cache shared:SSL:10m;
        ssl_session_timeout 10m;

        location / {
            proxy_pass http://app;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-CSRFToken $cookie_csrf_token;
            add_header Access-Controll-Allow-Origin * always;
            add_header Access-Controll-Allow-Methods "GET, POST, PUT, DELETE, OPTIONS" always;
            add_header Access-Control-Allow-Headers "DNT, User-Agent, X-Requestd-With, If-Modified-Since, Content-Type, Cahche-Control" always;

        }

        location /ws/ {
            proxy_pass http://app;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            add_header Access-Control-Allow-Origin * always;
            add_header Access-Control-Allow-Methods * always;
            add_header Access-Control-Allow-Headers "DNT, User-Agent, X-Requestd-With, If-Modified-Since, Content-Type, Cahche-Control" always;

            proxy_read_timeout 60000s;
            proxy_send_timeout 60000s;
            proxy_connect_timeout 60s;
            proxy_buffering off;
            proxy_request_buffering off;
        }

        location /static/ {
            alias /code/static/;
            autoindex on;
            types {
                text/css css;
                application/javascript js;
                image/svg+xml svg;
            }
        }
    }
}